[package]
name = "find_first_and_last_position_of_element_in_sorted_array"
version = "0.1.0"
edition = "2024"

[dependencies]


[[bin]]
name = "find_first_and_last_position_of_element_in_sorted_array"
path = "src/bin/execute.rs"